---
title: "R Motel Exercise"
format: pdf
editor: visual
---

------------------------------------------------------------------------

### Packages

```{r}
library(tidyverse)
library(multcomp)
library(mosaic)
```

------------------------------------------------------------------------

### Data

```{r}
rm(list=ls())
browseURL("http://www.principlesofeconometrics.com/poe5/data/def/motel.def")
load(url("http://www.principlesofeconometrics.com/poe5/data/rdata/motel.rdata"))

head(motel)
```

------------------------------------------------------------------------

### Exercise

Our hotel has 100 units. Repair period of 7 months of around 14 rooms. Question: Did this affect occupancy rates and revenue. Quantify losses.

How much revenue did the motel lose due to construction? Consider economic theory about hotel demand, role of pricing and competition, and how to isolate the impact of the repairs from other market factors.

------------------------------------------------------------------------

### Assumption:

-   Occupancy rate is on the number of available rooms (100 and 86)

------------------------------------------------------------------------

### Create variables for further usage

1. Create total number of rooms depending on repair.
2. Create occupied rooms from total number of rooms and occupancy.
3. Create revenue from occupied rooms and motel price.
4. Create relative occupancy between compatitors.

```{r}
# Total rooms
motel$TRoom <- 100 - 14*motel$repair

# Occupied rooms
motel$OcRoom <- motel$TRoom * motel$motel_pct / 100

# Revenue
motel$Revenue <- motel$OcRoom * motel$motel_rate

# Relative occupancy
motel$RelOcc <- motel$motel_pct / motel$comp_pct

# Renaming and changing for Usabilty
names(motel)[names(motel) == "comp_pct"] <- "CompOcc"
names(motel)[names(motel) == "motel_pct"] <- "MotelOcc"
names(motel)[names(motel) == "comp_rate"] <- "MotelPrice"
names(motel)[names(motel) == "motel_rate"] <- "CompPrice"
names(motel)[names(motel) == "relprice"] <- "RelPrice"

motel <- motel[, c("time", "days", "MotelPrice", "CompPrice",
                 "RelPrice", "MotelOcc", "CompOcc", "RelOcc", "repair",
                 "TRoom", "OcRoom", "Revenue"
                 )]

```

------------------------------------------------------------------------

### Analysis

1. Separate into before and after construction and show mean occupancy rate before and after repairs.

```{r}
motel_before <- motel %>% filter(repair==0)
motel_after  <- motel %<% filter(repair==1)

diffmean(MotelOcc ~ repair, data = motel)

```

2. First baseline regressions

$$
Revenue = \beta_0 + \beta_1 \cdot repair + \varepsilon \\
mean(Occupancy) = \beta_0 + \beta_1 \cdot repair + \varepsilon
$$

```{r}
# Baseline linear regressions
baseline_revenue_model   <- lm(Revenue ~ repair, data = motel)
baseline_occupancy_model <- lm(MotelOcc ~ repair, data = motel)

# Show results of linear Regressions
summary(baseline_revenue_model)
summary(baseline_occupancy_model)

# Show hypothesis testing H0 >= 0, vs H1 < 0 (left sided test)
summary(glht(baseline_revenue_model,linfct = c("repair >= 0")))
summary(glht(baseline_occupancy_model,linfct = c("repair >= 0")))

# Critical values, when alpha = 5%
qt(0.05, df= baseline_revenue_model$df.residual)
qt(0.05, df= baseline_occupancy_model$df.residual)
```





------------------------------------------------------------------------












